synonym_lookup = {
    "python": {"python programming", "py", "python"},
    "java": {"java programming", "jdk", "java"},
    "c++": {"cpp", "c plus plus", "c++"},
    "c#": {"c sharp", "dotnet", "c#.net", "c#"},
    "javascript": {"js", "ecmascript", "javascript"},
    "typescript": {"ts", "typed javascript", "typescript"},
    "ruby": {"ruby programming", "ruby language", "ruby"},
    "php": {"php programming", "php language", "php"},
    "swift": {"swift programming", "ios development", "swift"},
    "kotlin": {"android kotlin", "kotlin language", "kotlin"},
    "dart": {"dart programming", "dart"},
    "go": {"golang", "go programming", "go"},
    "rust": {"rust programming", "rust"},
    "r": {"r programming", "data analysis", "r"},
    "scala": {"scala programming", "scala"},
    "perl": {"perl programming", "perl"},
    "objective-c": {"objc", "objective-c", "objective c"},
    "matlab": {"matlab programming", "numerical computing", "matlab"},
    "assembly": {"asm", "assembly language", "assembly"},
    "bash": {"bash scripting", "shell scripts", "bash"},
    "powershell": {"powershell scripting", "powershell scripts", "powershell"},

    "react": {"react.js", "reactjs", "react library", "react"},
    "angular": {"angular framework", "angular.js", "angularjs", "angular"},
    "vue": {"vue.js", "vuejs", "vue"},
    "svelte": {"svelte.js", "svelte framework", "svelte"},
    "django": {"django framework", "django"},
    "flask": {"flask framework", "flask"},
    "fastapi": {"fastapi framework", "python web framework", "fastapi"},
    "express.js": {"express", "node.js framework", "express.js"},
    "next.js": {"nextjs", "next.js", "react server-side framework"},
    "nuxt.js": {"nuxtjs", "nuxt.js", "vue server-side framework"},
    "laravel": {"laravel framework", "laravel php", "laravel"},
    "spring": {"spring framework", "spring boot", "spring mvc", "spring"},
    "asp.net": {"asp.net framework", "asp.net", "dotnet framework"},
    "ruby on rails": {"rails", "ror", "ruby on rails"},

    "html": {"html5", "markup language", "html"},
    "css": {"css3", "cascading style sheets", "css"},
    "sass": {"scss", "css preprocessor", "sass"},
    "tailwind": {"tailwindcss", "tailwind framework", "tailwind"},
    "bootstrap": {"bootstrap framework", "css framework", "bootstrap"},
    "material-ui": {"mui", "material design", "material-ui"},
    "foundation": {"foundation css framework", "foundation"},
    
    "node.js": {"node", "nodejs", "server-side javascript", "node.js"},
    "graphql": {"graph query language", "graphql api", "graphql"},
    "rest api": {"restful services", "rest architecture", "rest api"},
    "elasticsearch": {"elastic stack", "search engine", "elasticsearch"},
    "redis": {"in-memory database", "key-value store", "redis"},
    "rabbitmq": {"message broker", "rabbit message queue", "rabbitmq"},
    "apache kafka": {"kafka", "event streaming", "apache kafka"},
    "nginx": {"nginx server", "web server", "nginx"},
    
    "aws": {"amazon web services", "cloud computing", "aws cloud", "aws"},
    "azure": {"microsoft azure", "cloud platform", "azure cloud", "azure"},
    "gcp": {"google cloud platform", "google cloud", "gcp"},
    "docker": {"containerization", "docker containers", "docker"},
    "kubernetes": {"k8s", "container orchestration", "kubernetes"},
    "terraform": {"iac", "infrastructure as code", "terraform configuration", "terraform"},
    "ansible": {"ansible automation", "ansible playbooks", "ansible"},
    "jenkins": {"jenkins ci", "continuous integration", "jenkins"},
    "github actions": {"ci/cd pipelines", "github workflows", "github actions"},

    "mysql": {"sql", "mysql database", "mysql"},
    "postgresql": {"postgres", "postgresql database", "postgresql"},
    "sqlite": {"sqlite3", "lightweight database", "sqlite"},
    "mongodb": {"mongo", "nosql database", "mongodb"},
    "cassandra": {"apache cassandra", "nosql database", "cassandra"},
    "couchdb": {"apache couchdb", "nosql database", "couchdb"},
    "oracle": {"oracle database", "relational database", "oracle"},
    "mariadb": {"mariadb database", "mysql fork", "mariadb"},

    
    "machine learning": {"ml", "ai", "artificial intelligence", "machine learning"},
    "deep learning": {"neural networks", "dl", "tensorflow", "pytorch", "keras", "deep learning"},
    "tensorflow": {"tensorflow library", "machine learning framework", "tensorflow"},
    "pytorch": {"pytorch framework", "deep learning framework", "pytorch"},
    "scikit-learn": {"sklearn", "ml library", "scikit-learn"},
    "xgboost": {"gradient boosting", "xgboost library", "xgboost"},
    "openai": {"openai models", "chatgpt", "openai"},
    "huggingface": {"transformers", "nlp library", "huggingface"},
    "opencv": {"computer vision library", "opencv"},
    "nlp": {"natural language processing", "text mining", "nlp"},

 
    "git": {"version control", "git commands", "github", "gitlab", "git"},
    "ci/cd": {"continuous integration and deployment", "jenkins", "travis ci", "github actions", "ci/cd"},
    "cybersecurity": {"network security", "ethical hacking", "penetration testing", "cybersecurity"},
    "iot": {"internet of things", "iot devices", "iot platforms", "iot"},
    "blockchain": {"distributed ledger", "ethereum", "smart contracts", "blockchain"},
    "data visualization": {"tableau", "power bi", "data dashboards", "data visualization"},
    "robotics": {"robotics engineering", "automation", "robot programming", "robotics"},
    "game development": {"unity", "unreal engine", "game engines", "game development"},

    "ui design": {"user interface design", "ui design", "interface design"},
    "ux design": {"user experience design", "ux design", "experience design"},
    "wireframing": {"wireframe creation", "low-fidelity design", "wireframing"},
    "prototyping": {"interactive prototypes", "design mockups", "prototyping"},
    "visual design": {"ui visuals", "graphic user interface", "visual design"},
    "interaction design": {"ixd", "interaction patterns", "interaction design"},
    "usability testing": {"user testing", "usability analysis", "usability testing"},
    "information architecture": {"ia", "content structuring", "information architecture"},
    "responsive design": {"mobile-first design", "adaptive design", "responsive design"},
    "accessibility design": {"a11y", "inclusive design", "accessibility standards"},
    "design systems": {"design libraries", "component libraries", "design systems"},
    "user research": {"ux research", "user feedback", "user research"},
    "persona development": {"user personas", "audience profiles", "persona development"},
    "journey mapping": {"user journey maps", "experience mapping", "journey mapping"},

    "figma": {"design collaboration", "ui tool", "figma"},
    "adobe xd": {"xd", "adobe design", "adobe xd"},
    "sketch": {"sketch app", "sketch design", "sketch"},
    "invision": {"invision studio", "prototyping tool", "invision"},
    "axure": {"axure rp", "axure prototyping", "axure"},
    "balsamiq": {"balsamiq mockups", "wireframing tool", "balsamiq"},
    "zeplin": {"design handoff", "collaboration tool", "zeplin"},
    "mural": {"online whiteboard", "brainstorming tool", "mural"},
    "adobe photoshop": {"ps", "image editing", "adobe photoshop"},
    "adobe illustrator": {"ai", "vector design", "adobe illustrator"},
    "marvel": {"marvel app", "design prototyping", "marvel"},

    "html/css": {"markup and styling", "frontend basics", "html/css"},
    "javascript for ui": {"ui scripting", "interactive design", "javascript"},
    "sass/less": {"css preprocessor", "advanced css", "sass/less"},

    "a/b testing": {"split testing", "experiment design", "a/b testing"},
    "heatmaps": {"user behavior analysis", "website heatmaps", "heatmaps"},
    "analytics tools": {"google analytics", "user behavior tools", "analytics tools"},
    "heuristic evaluation": {"ux evaluation", "interface assessment", "heuristic evaluation"},

    "data analysis": {"data analytics", "data analyst", "data analysis"},
    "data wrangling": {"data cleaning", "data preprocessing", "data wrangling"},
    "excel": {"microsoft excel", "excel spreadsheet", "excel formulas"},
    "sql": {"structured query language", "sql database", "sql"},
    "power bi": {"powerbi", "microsoft power bi", "power bi"},
    "tableau": {"tableau software", "data visualization", "tableau"},
    "python": {"python data analysis", "python pandas", "python numpy"},
    "r": {"r programming", "data analysis in r", "r language"},
    "pandas": {"python pandas", "data manipulation", "pandas library"},
    "numpy": {"python numpy", "numerical computing", "numpy"},
    "matplotlib": {"matplotlib library", "python plotting", "matplotlib"},
    "seaborn": {"seaborn visualization", "seaborn python", "seaborn"},
    "power query": {"power query editor", "excel power query", "power query"},
    "data modeling": {"data models", "database modeling", "data modeling"},
    "etl": {"extract transform load", "etl process", "etl tools"},
    "business intelligence": {"bi", "business intelligence tools", "bi reporting"},
    "statistical analysis": {"statistics", "statistical modeling", "statistical analysis"},
    "forecasting": {"predictive analysis", "forecasting methods", "forecasting"},
    "google analytics": {"ga", "google analytics", "web analytics"},
    "big data": {"big data analysis", "big data tools", "hadoop"},
    "machine learning": {"ml", "data science", "machine learning"},
    "data mining": {"data extraction", "data mining techniques", "data mining"},
    "reporting": {"data reporting", "business reporting", "data reports"},
    "data visualization": {"data viz", "data graphics", "data visualizations"},
    "survey analysis": {"survey data analysis", "questionnaire analysis", "survey analytics"},
    "qlikview": {"qlik", "qlikview dashboard", "qlikview tools"},
    "data governance": {"data policies", "data quality", "data governance"},
    "data-driven insights": {"insight generation", "data insights", "insights"},
    "dashboards": {"interactive dashboards", "dashboard tools", "dashboard visualizations"},
    "data integrity": {"data accuracy", "data consistency", "data validation"},
    "statistical tools": {"SPSS", "SAS", "Minitab", "statistical tools"},
    "python visualization": {"python visualization tools", "matplotlib", "seaborn"},
    "databases": {"relational databases", "sql databases", "database management"},
    "excel pivot tables": {"pivot tables", "excel analysis", "excel pivot"}
}